// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Address struct {
	Add                  string   `protobuf:"bytes,1,opt,name=Add,proto3" json:"Add,omitempty"`
	HNo                  string   `protobuf:"bytes,2,opt,name=HNo,proto3" json:"HNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAdd() string {
	if m != nil {
		return m.Add
	}
	return ""
}

func (m *Address) GetHNo() string {
	if m != nil {
		return m.HNo
	}
	return ""
}

type Person struct {
	Name                 string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Age                  int32             `protobuf:"varint,2,opt,name=Age,proto3" json:"Age,omitempty"`
	Addr                 *Address          `protobuf:"bytes,3,opt,name=Addr,proto3" json:"Addr,omitempty"`
	NickName             []string          `protobuf:"bytes,4,rep,name=NickName,proto3" json:"NickName,omitempty"`
	Records              map[string]string `protobuf:"bytes,5,rep,name=Records,proto3" json:"Records,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c9e10cf24b1156d, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetAddr() *Address {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *Person) GetNickName() []string {
	if m != nil {
		return m.NickName
	}
	return nil
}

func (m *Person) GetRecords() map[string]string {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "main.Address")
	proto.RegisterType((*Person)(nil), "main.Person")
	proto.RegisterMapType((map[string]string)(nil), "main.Person.RecordsEntry")
}

func init() {
	proto.RegisterFile("person.proto", fileDescriptor_4c9e10cf24b1156d)
}

var fileDescriptor_4c9e10cf24b1156d = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0x2d, 0x2a,
	0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xd2,
	0xe5, 0x62, 0x77, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0x16, 0x12, 0xe0, 0x62, 0x06, 0x32, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x90, 0x88, 0x87, 0x5f, 0xbe, 0x04, 0x13, 0x44,
	0x04, 0xc8, 0x54, 0xba, 0xc7, 0xc8, 0xc5, 0x16, 0x00, 0x36, 0x45, 0x48, 0x88, 0x8b, 0xc5, 0x2f,
	0x31, 0x37, 0x15, 0xaa, 0x1e, 0xcc, 0x06, 0x1b, 0x91, 0x9e, 0x0a, 0xd6, 0xc0, 0x1a, 0x04, 0x62,
	0x0a, 0x29, 0x72, 0xb1, 0x80, 0xcc, 0x97, 0x60, 0x06, 0x0a, 0x71, 0x1b, 0xf1, 0xea, 0x81, 0x2c,
	0xd5, 0x83, 0xda, 0x18, 0x04, 0x96, 0x12, 0x92, 0xe2, 0xe2, 0xf0, 0xcb, 0x4c, 0xce, 0x06, 0x1b,
	0xc6, 0xa2, 0xc0, 0x0c, 0x34, 0x0c, 0xce, 0x17, 0x32, 0xe6, 0x62, 0x0f, 0x4a, 0x4d, 0xce, 0x2f,
	0x4a, 0x29, 0x96, 0x60, 0x05, 0x4a, 0x71, 0x1b, 0x49, 0x42, 0x4c, 0x80, 0xb8, 0x41, 0x0f, 0x2a,
	0xe7, 0x9a, 0x57, 0x52, 0x54, 0x19, 0x04, 0x53, 0x29, 0x65, 0xc5, 0xc5, 0x83, 0x2c, 0x01, 0x72,
	0x55, 0x76, 0x6a, 0x25, 0xcc, 0x63, 0x40, 0xa6, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69,
	0x2a, 0xd4, 0x6b, 0x10, 0x8e, 0x15, 0x93, 0x05, 0x63, 0x12, 0x1b, 0x38, 0x70, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xd1, 0xfc, 0x5b, 0x5f, 0x2c, 0x01, 0x00, 0x00,
}
